name: pdf_viewer_example
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

  
dependencies:
  flutter:
    sdk: flutter
  flutter_grid_button: 

  cupertino_icons: ^1.0.0
  fluttertoast: 8.0.3
  flutter_svg: ^0.21.0+1

  # display PDF
  flutter_pdfview: ^1.0.4
  pdf: ^1.4

  # path
  file_picker: ^2.1.6
  path: ^1.7.0
  path_provider: ^1.6.27

  # download PDF
  http: ^0.12.2

  # load from Firebase
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/coffeeBackground.png
    - assets/images/coffeeLogoEdited.png
    - assets/images/logo.svg
    - assets/images/coffeeBackgroundPlain.png
    - assets/images/coffeeStand.png
    - assets/images/coffeeStandEdited.png
    - assets/images/icon-facebook.svg
    - assets/pdf/1-converted.pdf
    - assets/images/bg.png
    - assets/images/calendar.png
    - assets/images/family_time.png
    - assets/images/friends.png
    - assets/images/lovely_time.png
    - assets/images/me_time.png
    - assets/images/team_time.png
    - assets/images/android.png
    - assets/images/youtube.png
    - assets/images/iphone.png
    - assets/images/wa.png
    - assets/images/phone.png
    - assets/images/yt.png
    - assets/images/imo.png
    - assets/images/whatsapp.png
    - assets/pdf/Camerapdf_trail.pdf